# Generated by Django 3.2.13 on 2022-06-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=25, verbose_name='Correo')),
            ],
        ),
    ]
