# Generated by Django 3.2.13 on 2022-06-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0002_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=40, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
